### ISSUE TITLE
[Suggestion] Capacitors charge other items in your inventory

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ProspectPyxis/CustomCapacitors#1]
While in your inventory, you can right click a capacitor to activate it. While active, it will charge any RF-powered item in your hotbar, offhand or armor slot. It also has an enchanted glow for easy identification.

The capacitor works while it's in the player's inventory, hotbar, offhand or bauble slot. It should probably have separate input speeds, output speeds and power loss options. If these aren't specified, it will default to the global ones.

**Comment by ProspectPyxis** [comment]
Implemented in 1.2.0, with two caveats:
* It can't be charged while in an inventory by itself, it can only charge other items.
* Baubles support is a no go for now, unfortunately. I'll be opening another issue for this in a bit.

Information on the wiki is pending.
