### ISSUE TITLE
An example file?

### ISSUE THREAD

**Issue by Fortist** [ProspectPyxis/CustomCapacitors#3]
Im not really good with Json and starting a file from scratch, is there an example file I can look at?

**Comment by Staegrin** [comment]
I have this for the test file. Still doesn't show up in the game though. I hope to find out where I went wrong.

id [string, cobble]
display_name [string, "cobble capacitor"]
description [string, null]
capacity [int, 10000]
max_input_rate [int, 100]
max_output_rate [int, 100]
base_color [string, "888C8D"]
trim_color [string, "C50A2A"]
storage_loss_type [string, "none"]
storage_loss_data [object]
input_loss_type [string, "none"]
input_loss_value [float, 0]
retain_energy [boolean, true]

**Comment by ProspectPyxis** [comment]
Just finished adding a couple example files to the wiki page, enjoy!
