### ISSUE TITLE
Crafttweaker recipe hints

### ISSUE THREAD

**Issue by Staegrin** [ProspectPyxis/CustomCapacitors#8]
![2019-03-29_21 29 47](https://user-images.githubusercontent.com/8494635/55260915-e5165300-5269-11e9-97f7-6aac72c0e0a5.png)
![2019-03-29_21 29 52](https://user-images.githubusercontent.com/8494635/55260916-e5165300-5269-11e9-890e-e01535546fd8.png)
recipe: recipes.addShaped(<customcapacitors:custom_capacitor>, [[<ore:bricksStone>, <quantumflux:craftingpiece:6>, <ore:bricksStone>], [<quantumflux:craftingpiece:6>, <ore:blockRedstone>, <quantumflux:craftingpiece:6>], [<ore:bricksStone>, <quantumflux:craftingpiece:6>, <ore:bricksStone>]]);

The capacitors have their name/type saved via NBT capid:"basic" not metadata example: customcapacitors:custom_capacitor:0 and customcapacitors:custom_capacitor:1

To make crafttweaker work with this mod .withTag({BlockEntityTag:{capid:"basic"}}) would be added if the name of the capacitor is basic. this hint might need to be added to the wiki or metadata needs to be implemented in the mod.

Sadly this still gives  error parsing. So I'm probably missing something.
val cap = <customcapacitors:custom_capacitor>;
val basic = cap.withTag({BlockEntityTag:{capid:"basic"}});
recipes.addShaped(basic, [[<ore:bricksStone>, <ore:gemDiamond>, <ore:bricksStone>], [<ore:gemDiamond>, <ore:blockRedstone>, <ore:gemDiamond>], [<ore:bricksStone>, <ore:gemDiamond>, <ore:bricksStone>]]);

**Comment by ProspectPyxis** [comment]
The best way to make a recipe for a capacitor would simply be to hold the capacitor in your hand and use the command `/ct hand`, and use the resulting string as your output item. I'll see about putting this somewhere on the wiki.

**Comment by Staegrin** [comment]
To give a working example 
recipes.addShaped(<customcapacitors:custom_capacitor>.withTag({BlockEntityTag: {capid: "basic"}}), [[<ore:bricksStone>, <ore:gemDiamond>, <ore:bricksStone>], [<ore:gemDiamond>, <ore:blockRedstone>, <ore:gemDiamond>], [<ore:bricksStone>, <ore:gemDiamond>, <ore:bricksStone>]]);

**Comment by ProspectPyxis** [comment]
One question, is that the entire thing or did you remove all the angle brackets? You should probably read up on some crafttweaker basics - for example, items need to be surrounded by angle brackets like such: `<customcapacitors:custom_capacitor>`

**Comment by Staegrin** [comment]
For some reason they were removed when hitting the comment button. Had to make clear to github it was code so it would display <>Here's the correct version.
`recipes.addShaped(<customcapacitors:custom_capacitor>.withTag({BlockEntityTag: {capid: "basic"}}), [[<ore:bricksStone>, <ore:gemDiamond>, <ore:bricksStone>], [<ore:gemDiamond>, <ore:blockRedstone>, <ore:gemDiamond>], [<ore:bricksStone>, <ore:gemDiamond>, <ore:bricksStone>]]);`

**Comment by ProspectPyxis** [comment]
And that statement is giving an error? If yes, can I see what it is?

**Comment by Staegrin** [comment]
No, the latest version is working and gives a valid recipe for the basic capacitor.
